name:                dbcleaner-persistent
version:             0.1.0.0
github:              "sestrella/dbcleaner-persistent"
license:             BSD3
author:              "Sebastián Estrella"
maintainer:          "sebas007estrella@gmail.com"
copyright:           "2018 Sebastián Estrella"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sestrella/dbcleaner-persistent#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - dbcleaner
    - exceptions
    - persistent
    - persistent-sqlite
    - monad-logger
    - resourcet
    - persistent-template

tests:
  dbcleaner-persistent-test:
    source-dirs:         test
    main:                Spec.hs
    other-modules:
      - Database.DBCleaner.PersistentSpec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbcleaner-persistent
    - hspec
    - monad-logger
    - persistent
    - persistent-template
    - persistent-sqlite
    - resourcet
